# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autosync.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(443, 494)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setSizeIncrement(QtCore.QSize(0, 0))
        Form.setBaseSize(QtCore.QSize(0, 0))
        Form.setWindowOpacity(1.0)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 421, 281))
        self.textEdit.setObjectName("textEdit")
        self.labeDir1 = QtWidgets.QLabel(Form)
        self.labeDir1.setGeometry(QtCore.QRect(22, 389, 126, 17))
        self.labeDir1.setObjectName("labeDir1")
        self.labelDir2 = QtWidgets.QLabel(Form)
        self.labelDir2.setGeometry(QtCore.QRect(22, 420, 126, 17))
        self.labelDir2.setObjectName("labelDir2")
        self.comboBox_work = QtWidgets.QComboBox(Form)
        self.comboBox_work.setGeometry(QtCore.QRect(163, 389, 261, 25))
        self.comboBox_work.setObjectName("comboBox_work")
        self.comboBox_mirror = QtWidgets.QComboBox(Form)
        self.comboBox_mirror.setGeometry(QtCore.QRect(163, 420, 261, 25))
        self.comboBox_mirror.setObjectName("comboBox_mirror")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(22, 349, 401, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.OkBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.OkBtn.setObjectName("OkBtn")
        self.horizontalLayout_2.addWidget(self.OkBtn)
        self.ResetBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.ResetBtn.setObjectName("ResetBtn")
        self.horizontalLayout_2.addWidget(self.ResetBtn)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 310, 401, 24))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioCopy = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioCopy.setObjectName("radioCopy")
        self.horizontalLayout_3.addWidget(self.radioCopy)
        self.radioMirror = QtWidgets.QRadioButton(self.layoutWidget1)
        self.radioMirror.setObjectName("radioMirror")
        self.horizontalLayout_3.addWidget(self.radioMirror)
        self.layoutWidget2 = QtWidgets.QWidget(Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 450, 401, 31))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StartBtn = QtWidgets.QPushButton(self.layoutWidget2)
        self.StartBtn.setObjectName("StartBtn")
        self.horizontalLayout.addWidget(self.StartBtn)
        self.StopBtn = QtWidgets.QPushButton(self.layoutWidget2)
        self.StopBtn.setObjectName("StopBtn")
        self.horizontalLayout.addWidget(self.StopBtn)
        self.btnQuit = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnQuit.setObjectName("btnQuit")
        self.horizontalLayout.addWidget(self.btnQuit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Зеркало, зеркало..."))
        self.labeDir1.setText(_translate("Form", "Рабочая директория:"))
        self.labelDir2.setText(_translate("Form", "Директория-зеркало:"))
        self.OkBtn.setText(_translate("Form", "&Ok"))
        self.ResetBtn.setText(_translate("Form", "&Сброс"))
        self.radioCopy.setText(_translate("Form", "&Снять копию"))
        self.radioMirror.setText(_translate("Form", "&В реальном времени"))
        self.StartBtn.setText(_translate("Form", "&Запуск"))
        self.StopBtn.setText(_translate("Form", "&Стоп"))
        self.btnQuit.setText(_translate("Form", "&Выход"))

